variables:
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA

stages:
  - build
  - release
  - test

before_script:
  - skopeo login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-docker:
  stage: build
  tags:
    - nix
  script:
    - nix build -L .#docker 2>&1 | ts -s
    - ((skopeo <./result --insecure-policy copy docker-archive:/dev/stdin docker://$CONTAINER_TEST_IMAGE) || (skopeo <./result --insecure-policy copy docker-archive:/dev/stdin docker://$CONTAINER_TEST_IMAGE)) 2>&1 | ts -s
  only:
    - branches
  except:
    - master

build-docker-master:
  stage: build
  tags:
    - nix
  script:
    - nix build -L .#docker 2>&1 | ts -s
    - ((skopeo <./result --insecure-policy copy docker-archive:/dev/stdin docker://$CONTAINER_IMAGE) || (skopeo <./result --insecure-policy copy docker-archive:/dev/stdin docker://$CONTAINER_IMAGE)) 2>&1 | ts -s
  except:
    - merge_requests
  only:
    - master

release-master-image:
  stage: release
  tags:
    - nix
  script: skopeo copy --insecure-policy docker://$CONTAINER_IMAGE docker://$CONTAINER_RELEASE_IMAGE
  only:
    - master

# Tag/Releases
released-tags-image:
  stage: release
  tags:
    - nix
  script: skopeo copy --insecure-policy docker://$CONTAINER_IMAGE docker://$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  only:
    - /^(\d+\.)?(\d+\.)?(\*|\d+)$/
  except:
    - branches
